config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  root 'contacts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
    @contacts = @contacts.where("name ilike '%#{params[:search]}%'") if params[:search]
    @contacts = @contacts.order(params[:sort].split("-").join(" ")) if params[:sort]
  end

  def show
    @contact = Contact.find(params[:id])
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :address, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fiel form-group">
    
    <%= form.text_field :name, class:"form-control",placeholder:"Full Name" %>
  </div>

  <div class="field">
   
    <%= form.text_area :address, class:"form-control",placeholder:"Address" %>
  </div>

  <div class="field">
   
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field">
    
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact, class:"btn btn-secondary" %> 
<%= link_to 'Back', contacts_path, class:"btn btn-dark" %>

app/views/contacts/index.html.erb
<%= form_tag(contacts_path, method: :get) do %>
  <p> Search for a contact </p>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search") %>
<% end %>

<br/>
<table class="table table-striped table-bordered table-hover">
<thead class="table-dark">
    <tr>
      <th><%= link_to "Name", params.permit(:search).merge({:sort=> (params[:sort] == "name" ? "name-desc" : "name")}) %></th>
      <th><%= link_to "Address", params.permit(:search).merge({:sort=> (params[:sort] == "address" ? "address-desc" : "address")}) %></th>
      <th><%= link_to "Email", params.permit(:search).merge({:sort=> (params[:sort] == "email" ? "email-desc" : "email")}) %></th>
      <th><%= link_to "Phone", params.permit(:search).merge({:sort=> (params[:sort] == "phone" ? "phone-desc" : "phone")}) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.address %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path, class:"btn btn-secondary" %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path, class:"btn btn-dark" %>

app/views/contacts/show.html.erb
<div class="jumbotron">
<h1 class="display-5"><%= @contact.name %> | <%= @contact.address %></h1>
<p class="lead">  <%= @contact.email %> | <%= @contact.phone %></p>

<br/>
<p>
<%= link_to 'Edit', edit_contact_path(@contact),class:"btn btn-secondary" %> 
<%= link_to 'Back', contacts_path, class:"btn btn-secondary" %>
</p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Contacts App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
       
	<li class="nav-item">
           <%= link_to 'Contacts', contacts_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to 'Add Contacts', new_contact_path, class:"nav-link" %>
        </li>
        
       
      </ul>
      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button> %>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissable fade show" role="alert">

	<%= notice %>
	
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">

		<span aria-hidden="true">&times;
	</span>
</button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Contacts App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <br/>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
      <%=render 'layouts/alerts' %>
      <% end %>

     <%= yield %>
</div>
 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>